
/*
 * This file was automatically generated by fun_gen.py
 * DO NOT CHANGE!
 */

#ifndef flowy_engine_auto_assign_h
#define flowy_engine_auto_assign_h

#include "base_header.h"

#include "flowy.h"
#include "auto_comps.h"

struct branch_info;

void assign_fptr(struct branch_info *binfos, int num_threads);

#endif
