
/*
 * This file was automatically generated by ../scripts/gen-ipfix-constants.py
 * DO NOT CHANGE!
 */



#include <string.h>

#include "ipfix-constants.h"

enum ipfix_ie_type
get_ipfix_type(const char* ie_name) {

    if (strcmp(ie_name, "VRFname") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "flowKeyIndicator") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "informationElementSemantics") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "flowStartMicroseconds") == 0)
        return IETYPE_DATETIMEMICROSECONDS;

    if (strcmp(ie_name, "ipPayloadPacketSection") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "upperCILimit") == 0)
        return IETYPE_FLOAT64;

    if (strcmp(ie_name, "ipTTL") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "observationTimeSeconds") == 0)
        return IETYPE_DATETIMESECONDS;

    if (strcmp(ie_name, "postMCastPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "tcpUrgTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "anonymizationFlags") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "postPacketDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "egressInterface") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "flowIdleTimeout") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "informationElementName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "responderOctets") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "collectionTimeMilliseconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "originalFlowsCompleted") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "flowId") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "monitoringIntervalStartMilliSeconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "tcpSourcePort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "tcpSequenceNumber") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "commonPropertiesId") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "ipVersion") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "octetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "flowDurationMilliseconds") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "egressInterfaceType") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "udpDestinationPort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "distinctCountOfDestinationIPv4Address") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "selectorIdTotalPktsObserved") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "ethernetPayloadLength") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "connectionCountNew") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "valueDistributionMethod") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "flowActiveTimeout") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "observationTimeMicroseconds") == 0)
        return IETYPE_DATETIMEMICROSECONDS;

    if (strcmp(ie_name, "dot1qCustomerDEI") == 0)
        return IETYPE_BOOLEAN;

    if (strcmp(ie_name, "sourceIPv6PrefixLength") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "rfc3550JitterMicroseconds") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "applicationGroupName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "minFlowStartMicroseconds") == 0)
        return IETYPE_DATETIMEMICROSECONDS;

    if (strcmp(ie_name, "egressBroadcastPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "dot1qCustomerPriority") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "tcpAckTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "collectorIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "hashSelectedRangeMax") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "pseudoWireId") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "rtpSequenceNumber") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "samplingPacketInterval") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "ingressMulticastPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "lowerCILimit") == 0)
        return IETYPE_FLOAT64;

    if (strcmp(ie_name, "p2pTechnology") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "samplingPacketSpace") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "selectionSequenceId") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "destinationIPv4PrefixLength") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "informationElementId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "encryptedTechnology") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "collectorIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "mplsTopLabelType") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "greKey") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "flowEndReason") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "postDestinationMacAddress") == 0)
        return IETYPE_MACADDRESS;

    if (strcmp(ie_name, "egressVRFID") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "hashIPPayloadSize") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "natPoolId") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "egressPhysicalInterface") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "mplsLabelStackSection8") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "selectorIdTotalPktsSelected") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "paddingOctets") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "hashOutputRangeMax") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "sourceIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "initiatorPackets") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "ingressInterface") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "destinationIPv4Prefix") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "ignoredPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "droppedPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "ipNextHopIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "bgpDestinationAsNumber") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "subTemplateMultiList") == 0)
        return IETYPE_SUBTEMPLATEMULTILIST;

    if (strcmp(ie_name, "octetDeltaSumOfSquares") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "mplsLabelStackSection10") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "virtualStationInterfaceId") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "ethernetTotalLength") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "firewallEvent") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "tcpFinTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "protocolIdentifier") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "droppedOctetDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "flowEndSeconds") == 0)
        return IETYPE_DATETIMESECONDS;

    if (strcmp(ie_name, "exporterIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "droppedOctetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postNAPTDestinationTransportPort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "sourceIPv4PrefixLength") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "dot1qDEI") == 0)
        return IETYPE_BOOLEAN;

    if (strcmp(ie_name, "flowDirection") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "ethernetHeaderLength") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "igmpType") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "octetTotalSumOfSquares") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "selectorName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "interfaceDescription") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "icmpCodeIPv6") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "exportedOctetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "applicationSubCategoryName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "ethernetType") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "hashDigestOutput") == 0)
        return IETYPE_BOOLEAN;

    if (strcmp(ie_name, "udpMessageLength") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "minimumTTL") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "samplingPopulation") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "maxFlowEndMilliseconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "minimumIpTotalLength") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postIpClassOfService") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "connectionTransactionId") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "destinationIPv6Prefix") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "observationDomainId") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "originalFlowsPresent") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "natPoolName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "messageMD5Checksum") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "mplsLabelStackSection9") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "exporterCertificate") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "mplsLabelStackSection7") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "mplsLabelStackSection6") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "mplsLabelStackSection5") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "mplsLabelStackSection4") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "mplsLabelStackSection3") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "mplsLabelStackSection2") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "exportedFlowRecordTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "interfaceName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "relativeError") == 0)
        return IETYPE_FLOAT64;

    if (strcmp(ie_name, "sourceIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "virtualStationName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "fragmentOffset") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "tcpPshTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "informationElementRangeEnd") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "hashSelectedRangeMin") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "applicationName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "portId") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "postDot1qCustomerVlanId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "notSentFlowTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "tcpWindowScale") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "ingressVRFID") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "deltaFlowCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postIpPrecedence") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "hashInitialiserValue") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "exportSctpStreamId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "observationTimeNanoseconds") == 0)
        return IETYPE_DATETIMENANOSECONDS;

    if (strcmp(ie_name, "destinationIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "anonymizationTechnique") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "natEvent") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "sourceIPv6Prefix") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "notSentPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "dataLinkFrameSection") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "mplsPayloadPacketSection") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "portRangeStart") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "ingressBroadcastPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "systemInitTimeMilliseconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "informationElementDescription") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "ipDiffServCodePoint") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "destinationTransportPort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "dataRecordsReliability") == 0)
        return IETYPE_BOOLEAN;

    if (strcmp(ie_name, "natOriginatingAddressRealm") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "IPSecSPI") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "maxFlowEndSeconds") == 0)
        return IETYPE_DATETIMESECONDS;

    if (strcmp(ie_name, "collectorTransportPort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "ipNextHopIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "destinationIPv6PrefixLength") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "tcpUrgentPointer") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "observationDomainName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "userName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "bgpValidityState") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "portRangeStepSize") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "dot1qVlanId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "observedFlowTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "tcpRstTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "informationElementDataType") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "pseudoWireControlWord") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "digestHashValue") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "exportProtocolVersion") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "samplingProbability") == 0)
        return IETYPE_FLOAT64;

    if (strcmp(ie_name, "postIpDiffServCodePoint") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "destinationIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "postNAPTSourceTransportPort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "messageScope") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "observationPointType") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "tcpOptions") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "ipHeaderPacketSection") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "ipTotalLength") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "packetDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "ignoredOctetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "distinctCountOfDestinationIPv6Address") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "distinctCountOfSourceIPv6Address") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "tcpHeaderLength") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "ipHeaderLength") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "hashOutputRangeMin") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postMCastPacketDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "pseudoWireType") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "staMacAddress") == 0)
        return IETYPE_MACADDRESS;

    if (strcmp(ie_name, "observationPointId") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "icmpTypeCodeIPv4") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "icmpTypeCodeIPv6") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "payloadLengthIPv6") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "biflowDirection") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "opaqueOctets") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "flowEndSysUpTime") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "postNATSourceIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "informationElementRangeBegin") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "metroEvcType") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "bgpSourceAsNumber") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "samplingSize") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "wtpMacAddress") == 0)
        return IETYPE_MACADDRESS;

    if (strcmp(ie_name, "layer2OctetDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "tcpControlBits") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "virtualStationUUID") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "layer2SegmentId") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "initiatorOctets") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "ipv4IHL") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "destinationMacAddress") == 0)
        return IETYPE_MACADDRESS;

    if (strcmp(ie_name, "flowStartMilliseconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "virtualStationInterfaceName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "ipPrecedence") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "absoluteError") == 0)
        return IETYPE_FLOAT64;

    if (strcmp(ie_name, "templateId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "selectorId") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "meteringProcessId") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "isMulticast") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "applicationId") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "samplingTimeInterval") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "classificationEngineId") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "metroEvcId") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "collectorCertificate") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "dot1qPriority") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "minExportSeconds") == 0)
        return IETYPE_DATETIMESECONDS;

    if (strcmp(ie_name, "minFlowStartNanoseconds") == 0)
        return IETYPE_DATETIMENANOSECONDS;

    if (strcmp(ie_name, "totalLengthIPv4") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "tcpSynTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "exportingProcessId") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "postMplsTopLabelExp") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "mplsLabelStackDepth") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "originalFlowsInitiated") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postNATSourceIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "mplsLabelStackLength") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "privateEnterpriseNumber") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "mplsTopLabelIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "dataLinkFrameSize") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "postNATDestinationIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "exportTransportProtocol") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "flowEndNanoseconds") == 0)
        return IETYPE_DATETIMENANOSECONDS;

    if (strcmp(ie_name, "wlanChannelId") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "flowStartSeconds") == 0)
        return IETYPE_DATETIMESECONDS;

    if (strcmp(ie_name, "mplsTopLabelStackSection") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "lineCardId") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "distinctCountOfSourceIPv4Address") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "exporterIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "hashIPPayloadOffset") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "ingressPhysicalInterface") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "udpSourcePort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "bgpNextHopIPv6Address") == 0)
        return IETYPE_IPV6ADDRESS;

    if (strcmp(ie_name, "flowEndDeltaMicroseconds") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "tunnelTechnology") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "portRangeEnd") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "flowStartSysUpTime") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "dot1qCustomerVlanId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "rfc3550JitterNanoseconds") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "tcpAcknowledgementNumber") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "portRangeNumPorts") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "samplingTimeSpace") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "applicationDescription") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "bgpNextAdjacentAsNumber") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "flowDurationMicroseconds") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "packetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "informationElementUnits") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "mplsVpnRouteDistinguisher") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "postOctetDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "mplsTopLabelTTL") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "mplsTopLabelIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "bgpNextHopIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "ipClassOfService") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "wlanSSID") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "flowEndMicroseconds") == 0)
        return IETYPE_DATETIMEMICROSECONDS;

    if (strcmp(ie_name, "ingressUnicastPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "minFlowStartMilliseconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "confidenceLevel") == 0)
        return IETYPE_FLOAT64;

    if (strcmp(ie_name, "icmpCodeIPv4") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "exportInterface") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "rfc3550JitterMilliseconds") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "mplsTopLabelExp") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "nextHeaderIPv6") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "sourceIPv4Prefix") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "ipPayloadLength") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "tcpDestinationPort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "fragmentFlags") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "observationTimeMilliseconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "multicastReplicationFactor") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "tcpWindowSize") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "bgpPrevAdjacentAsNumber") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "flowEndMilliseconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "maxExportSeconds") == 0)
        return IETYPE_DATETIMESECONDS;

    if (strcmp(ie_name, "fragmentIdentification") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "selectorAlgorithm") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "minFlowStartSeconds") == 0)
        return IETYPE_DATETIMESECONDS;

    if (strcmp(ie_name, "sourceMacAddress") == 0)
        return IETYPE_MACADDRESS;

    if (strcmp(ie_name, "postOctetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "flowStartNanoseconds") == 0)
        return IETYPE_DATETIMENANOSECONDS;

    if (strcmp(ie_name, "ingressInterfaceType") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "basicList") == 0)
        return IETYPE_BASICLIST;

    if (strcmp(ie_name, "maxFlowEndMicroseconds") == 0)
        return IETYPE_DATETIMEMICROSECONDS;

    if (strcmp(ie_name, "postMCastOctetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "maximumTTL") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "postMCastOctetDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "octetDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "egressUnicastPacketTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "staIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "natType") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "responderPackets") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "vlanId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "subTemplateList") == 0)
        return IETYPE_SUBTEMPLATELIST;

    if (strcmp(ie_name, "ipv4Options") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "postVlanId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "icmpTypeIPv6") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "exporterTransportPort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "icmpTypeIPv4") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "sourceTransportPort") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "distinctCountOfDestinationIPAddress") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "flowStartDeltaMicroseconds") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "exportedMessageTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "notSentOctetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "connectionSumDuration") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postSourceMacAddress") == 0)
        return IETYPE_MACADDRESS;

    if (strcmp(ie_name, "sessionScope") == 0)
        return IETYPE_UNSIGNED8;

    if (strcmp(ie_name, "mplsPayloadLength") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "droppedPacketDeltaCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postNATDestinationIPv4Address") == 0)
        return IETYPE_IPV4ADDRESS;

    if (strcmp(ie_name, "applicationCategoryName") == 0)
        return IETYPE_STRING;

    if (strcmp(ie_name, "informationElementIndex") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "layer2OctetTotalCount") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "monitoringIntervalEndMilliSeconds") == 0)
        return IETYPE_DATETIMEMILLISECONDS;

    if (strcmp(ie_name, "maxFlowEndNanoseconds") == 0)
        return IETYPE_DATETIMENANOSECONDS;

    if (strcmp(ie_name, "flowLabelIPv6") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "ipv6ExtensionHeaders") == 0)
        return IETYPE_UNSIGNED32;

    if (strcmp(ie_name, "mplsLabelStackSection") == 0)
        return IETYPE_OCTETARRAY;

    if (strcmp(ie_name, "distinctCountOfSourceIPAddress") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "maximumIpTotalLength") == 0)
        return IETYPE_UNSIGNED64;

    if (strcmp(ie_name, "postDot1qVlanId") == 0)
        return IETYPE_UNSIGNED16;

    if (strcmp(ie_name, "mplsTopLabelPrefixLength") == 0)
        return IETYPE_UNSIGNED8;

    return IETYPE_UNKNOWN;
}
