
/*
 * This file was automatically generated by ../scripts/gen-ipfix-constants.py
 * DO NOT CHANGE!
 */


#ifndef f_engine_ipfix_constants_h
#define f_engine_ipfix_constants_h

#define MAX_IPFIX_IES     342

enum ipfix_ie_type {
    IETYPE_UNKNOWN,
    IETYPE_STRING,
    IETYPE_UNSIGNED64,
    IETYPE_UNSIGNED8,
    IETYPE_DATETIMEMICROSECONDS,
    IETYPE_OCTETARRAY,
    IETYPE_FLOAT64,
    IETYPE_DATETIMESECONDS,
    IETYPE_UNSIGNED16,
    IETYPE_UNSIGNED32,
    IETYPE_DATETIMEMILLISECONDS,
    IETYPE_BOOLEAN,
    IETYPE_IPV6ADDRESS,
    IETYPE_IPV4ADDRESS,
    IETYPE_MACADDRESS,
    IETYPE_SUBTEMPLATEMULTILIST,
    IETYPE_DATETIMENANOSECONDS,
    IETYPE_BASICLIST,
    IETYPE_SUBTEMPLATELIST,
};

enum ipfix_ie_type
get_ipfix_type(const char *ie_name);

#endif // ! f_engine_ipfix_constants_h
