
/*
 * This file was automatically generated by fun_gen.py
 * DO NOT CHANGE!
 */

#ifndef flowy_engine_auto_assign_h
#define flowy_engine_auto_assign_h

#include "auto_comps.h"

void
assign_fptr(struct flowquery *fquery);

struct aggr* 
(*get_aggr_fptr(bool ifgrouper,
                uint64_t op))(char **records,
                              char *group_aggregation,
                              size_t num_records,
                              size_t field_offset,
                              bool if_aggr_common);

#endif
