
/*
 * This file was automatically generated by fun_gen.py
 * DO NOT CHANGE!
 */

#ifndef flowy_engine_auto_assign_h
#define flowy_engine_auto_assign_h

#include "auto_comps.h"
#include "grouper.h"

struct grouper_intermediate_result;

void
assign_fptr(struct flowquery *fquery);

struct aggr* 
(*get_aggr_fptr(bool ifgrouper,
                uint64_t op))(char **records,
                              char *group_aggregation,
                              size_t num_records,
                              size_t field_offset,
                              bool if_aggr_common);


struct grouper_type* get_gtype(uint64_t op);

#endif
