
/*
 * This file was automatically generated by fun_gen.py
 * DO NOT CHANGE!
 */

#ifndef flowy_engine_auto_assign_h
#define flowy_engine_auto_assign_h

#include "auto_comps.h"
#include "grouper.h"

struct grouper_intermediate_result;

void 
assign_filter_func(struct filter_rule* const frule);

void 
assign_grouper_func(struct grouper_rule* const grule);

void 
assign_aggr_func(struct aggr_rule* const arule);

void 
assign_gfilter_func(struct gfilter_rule* const gfrule);

void 
assign_merger_func(struct merger_rule* const mrule);

struct aggr* 
(*get_aggr_fptr(bool ifgrouper,
                uint64_t op))(char **records,
                              char *group_aggregation,
                              size_t num_records,
                              size_t field_offset,
                              bool if_aggr_common);

struct grouper_type* get_gtype(uint64_t op);

#endif
